import type { StaffEmployee } from "@/lib/staff";

// Seeded from the staff directory spreadsheet. Values are stored as entered.
export const staffRoster: StaffEmployee[] = [
  {
    id: "roster-1",
    fullName: "Deep Rai",
    firstName: "Deep",
    lastName: "Rai",
    nationality: "Nepalese",
    dateOfBirth: "1992-09-13",
    joiningDate: "2020-02-01",
    position: "Jnr Sous Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 7200,
    allowances: 4800,
    salary: 12000,
  },
  {
    id: "roster-2",
    fullName: "Eranga Prasad Ruparathna Katumetiyawe Patabedi Gedara",
    firstName: "Eranga",
    lastName: "Gedara",
    nationality: "Sri Lankan",
    dateOfBirth: "1990-01-01",
    joiningDate: "2020-07-08",
    position: "Chef de Partie",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-3",
    fullName: "Ragesh Velayudhan",
    firstName: "Ragesh",
    lastName: "Velayudhan",
    nationality: "Indian",
    dateOfBirth: "1984-05-15",
    joiningDate: "2019-10-25",
    position: "Demi Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-4",
    fullName: "Sreejath Sivakumar",
    firstName: "Sreejath",
    lastName: "Sivakumar",
    nationality: "Indian",
    dateOfBirth: "1997-05-11",
    joiningDate: "2021-10-24",
    position: "Demi Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-5",
    fullName: "Vilas Abbathini",
    firstName: "Vilas",
    lastName: "Abbathini",
    nationality: "Indian",
    dateOfBirth: "1993-04-08",
    joiningDate: "2023-12-01",
    position: "Demi Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-6",
    fullName: "Ahmed Yasser Said Hassanein Daker",
    firstName: "Ahmed",
    lastName: "Daker",
    nationality: "Egyptian",
    dateOfBirth: "2002-12-14",
    joiningDate: "2024-02-16",
    position: "Demi Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-7",
    fullName: "Andres Felipe Gaitan Tabares",
    firstName: "Andres",
    lastName: "Tabares",
    nationality: "Colombian",
    dateOfBirth: "1994-04-16",
    joiningDate: "2024-10-01",
    position: "Demi Chef",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-8",
    fullName: "Prashan Tharindu Dayarathne Pincha Dewage",
    firstName: "Prashan",
    lastName: "Dewage",
    nationality: "Sri Lankan",
    dateOfBirth: "1999-12-30",
    joiningDate: "2025-12-04",
    position: "Commis 1",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-9",
    fullName: "Bhupal Gharti Chhetri",
    firstName: "Bhupal",
    lastName: "Chhetri",
    nationality: "Nepalese",
    dateOfBirth: "1988-09-20",
    joiningDate: "2022-01-10",
    position: "Commis 1",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-10",
    fullName: "Enisha K C",
    firstName: "Enisha",
    lastName: "C",
    nationality: "Nepalese",
    dateOfBirth: "1998-03-31",
    joiningDate: "2026-01-05",
    position: "Commis 2",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-11",
    fullName: "Arslan Ali Ehsan Ullah",
    firstName: "Arslan",
    lastName: "Ullah",
    nationality: "Pakistani",
    dateOfBirth: "1997-01-13",
    joiningDate: "2022-10-20",
    position: "Commis 3",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-12",
    fullName: "Arth Joseph Urmido Pastrana",
    firstName: "Arth",
    lastName: "Pastrana",
    nationality: "Filipino",
    dateOfBirth: "1997-10-31",
    joiningDate: "2024-08-01",
    position: "Commis 3",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-13",
    fullName: "Banuka Ravidu Eshan Madduma Welage",
    firstName: "Banuka",
    lastName: "Welage",
    nationality: "Sri Lankan",
    dateOfBirth: "1997-12-04",
    joiningDate: "2025-01-01",
    position: "Commis 3",
    venue: "The MAINE Land Brasserie",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-14",
    fullName: "Kundan Singh Anoop Singh",
    firstName: "Kundan",
    lastName: "Singh",
    nationality: "Indian",
    dateOfBirth: "1986-11-03",
    joiningDate: "2018-01-24",
    position: "Sous Chef",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 9000,
    allowances: 6000,
    salary: 15000,
  },
  {
    id: "roster-15",
    fullName: "Kuldip Ale",
    firstName: "Kuldip",
    lastName: "Ale",
    nationality: "Nepalese",
    dateOfBirth: "1992-05-21",
    joiningDate: "2017-07-21",
    position: "Chef de Partie",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-16",
    fullName: "Kattya Viviana Pisco Sedano",
    firstName: "Kattya",
    lastName: "Sedano",
    nationality: "Peruvian",
    dateOfBirth: "1991-04-30",
    joiningDate: "2025-11-01",
    position: "Chef de Partie",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-17",
    fullName: "Aymen Cheikh",
    firstName: "Aymen",
    lastName: "Cheikh",
    nationality: "N/A",
    dateOfBirth: "2026-08-06",
    joiningDate: "2025-12-15",
    position: "Demi Chef",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 3900,
    allowances: 2600,
    salary: 6500,
  },
  {
    id: "roster-18",
    fullName: "Rohan Bagla",
    firstName: "Rohan",
    lastName: "Bagla",
    nationality: "Indian",
    dateOfBirth: "1998-02-14",
    joiningDate: "2026-01-15",
    position: "Demi Chef",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-19",
    fullName: "Maharani Permatasari",
    firstName: "Maharani",
    lastName: "Permatasari",
    nationality: "Indonesian",
    dateOfBirth: "2000-01-17",
    joiningDate: "2022-08-04",
    position: "Demi Chef",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-20",
    fullName: "Ayesh Dilshan De Silva Kammanthi",
    firstName: "Ayesh",
    lastName: "Kammanthi",
    nationality: "Sri Lankan",
    dateOfBirth: "1998-09-21",
    joiningDate: "2025-11-01",
    position: "Commis 1",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-21",
    fullName: "Erika Lorena Marin Hernandez",
    firstName: "Erika",
    lastName: "Hernandez",
    nationality: "Colombian",
    dateOfBirth: "1993-08-24",
    joiningDate: "2024-11-20",
    position: "Commis 1",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-22",
    fullName: "Vinay Kumar Sripadham Yadagiri Sripadham",
    firstName: "Vinay",
    lastName: "Sripadham",
    nationality: "Indian",
    dateOfBirth: "1992-07-04",
    joiningDate: "2022-01-27",
    position: "Commis 2",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-23",
    fullName: "Desmond Emraan Newman",
    firstName: "Desmond",
    lastName: "Newman",
    nationality: "Sri Lankan",
    dateOfBirth: "1991-07-06",
    joiningDate: "2025-11-01",
    position: "Commis 2",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-24",
    fullName: "Deepak Oli Ram Bahadur Oli",
    firstName: "Deepak",
    lastName: "Oli",
    nationality: "Nepalese",
    dateOfBirth: "1990-05-26",
    joiningDate: "2021-11-10",
    position: "Commis 2",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-25",
    fullName: "Rashmi Praboda Silva Kandauda Arachchige",
    firstName: "Rashmi",
    lastName: "Arachchige",
    nationality: "Sri Lankan",
    dateOfBirth: "2001-11-13",
    joiningDate: "2023-07-10",
    position: "Commis 3",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-26",
    fullName: "Bikky D C",
    firstName: "Bikky",
    lastName: "C",
    nationality: "Nepalese",
    dateOfBirth: "1990-06-19",
    joiningDate: "2021-10-20",
    position: "Steward",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 1800,
    allowances: 1200,
    salary: 3000,
  },
  {
    id: "roster-27",
    fullName: "Naresh Karki",
    firstName: "Naresh",
    lastName: "Karki",
    nationality: "Nepalese",
    dateOfBirth: "2002-04-17",
    joiningDate: "2026-08-05",
    position: "Steward",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 1500,
    allowances: 1000,
    salary: 2500,
  },
  {
    id: "roster-28",
    fullName: "Bishnu Bahadur Thapa",
    firstName: "Bishnu",
    lastName: "Thapa",
    nationality: "Nepalese",
    dateOfBirth: "1983-03-19",
    joiningDate: "2023-04-01",
    position: "Steward",
    venue: "The MAINE Oyster Bar & Grill",
    photo: null,
    basicSalary: 1680,
    allowances: 1120,
    salary: 2800,
  },
  {
    id: "roster-29",
    fullName: "Veeram Reddy",
    firstName: "Veeram",
    lastName: "Reddy",
    nationality: "Indian",
    dateOfBirth: "1998-02-20",
    joiningDate: "2019-02-11",
    position: "Head Chef",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 12000,
    allowances: 8000,
    salary: 20000,
  },
  {
    id: "roster-30",
    fullName: "Manisha Harpreet",
    firstName: "Manisha",
    lastName: "Harpreet",
    nationality: "Indian",
    dateOfBirth: "1998-07-12",
    joiningDate: "2025-11-24",
    position: "Demi Chef",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-31",
    fullName: "Deb Bahadur Gurung",
    firstName: "Deb",
    lastName: "Gurung",
    nationality: "Nepalese",
    dateOfBirth: "1986-12-31",
    joiningDate: "2020-06-13",
    position: "Commis 1",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-32",
    fullName: "Gauravansh Singh",
    firstName: "Gauravansh",
    lastName: "Singh",
    nationality: "Indian",
    dateOfBirth: "1999-07-03",
    joiningDate: "2023-06-15",
    position: "Commis 2",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-33",
    fullName: "Nitin Singh",
    firstName: "Nitin",
    lastName: "Singh",
    nationality: "Indian",
    dateOfBirth: "2000-08-22",
    joiningDate: "2025-11-18",
    position: "Commis 3",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-34",
    fullName: "Anton Go",
    firstName: "Anton",
    lastName: "Go",
    nationality: "Filipino",
    dateOfBirth: "1998-09-16",
    joiningDate: "2025-04-01",
    position: "Commis 3",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-35",
    fullName: "Theekshana Dulshan Bala Patabendige",
    firstName: "Theekshana",
    lastName: "Patabendige",
    nationality: "Sri Lankan",
    dateOfBirth: "2004-03-21",
    joiningDate: "2025-11-01",
    position: "Commis 3",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-36",
    fullName: "Dinesh Nidamanuri",
    firstName: "Dinesh",
    lastName: "Nidamanuri",
    nationality: "Indian",
    dateOfBirth: "2004-08-03",
    joiningDate: "2025-11-01",
    position: "Commis 3",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-37",
    fullName: "Mubashir Ali",
    firstName: "Mubashir",
    lastName: "Ali",
    nationality: "Pakistani",
    dateOfBirth: "",
    joiningDate: "2025-12-01",
    position: "Steward",
    venue: "The MAINE Street Eatery",
    photo: null,
    basicSalary: 1680,
    allowances: 1120,
    salary: 2800,
  },
  {
    id: "roster-38",
    fullName: "Mahendra Singh Negi",
    firstName: "Mahendra",
    lastName: "Negi",
    nationality: "Indian",
    dateOfBirth: "",
    joiningDate: "2019-02-22",
    position: "Head Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 12000,
    allowances: 8000,
    salary: 20000,
  },
  {
    id: "roster-39",
    fullName: "Sudhan Siwa",
    firstName: "Sudhan",
    lastName: "Siwa",
    nationality: "Nepalese",
    dateOfBirth: "1993-03-15",
    joiningDate: "2025-11-01",
    position: "Sous Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 8700,
    allowances: 5800,
    salary: 14500,
  },
  {
    id: "roster-40",
    fullName: "Bryan Aldrich Basa",
    firstName: "Bryan",
    lastName: "Basa",
    nationality: "Filipino",
    dateOfBirth: "",
    joiningDate: "2020-03-01",
    position: "Jnr Sous Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 6600,
    allowances: 4400,
    salary: 11000,
  },
  {
    id: "roster-41",
    fullName: "Ishara Madushan Doraka Gamage",
    firstName: "Ishara",
    lastName: "Gamage",
    nationality: "Sri Lankan",
    dateOfBirth: "1992-12-14",
    joiningDate: "2025-11-01",
    position: "Pastry Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 6600,
    allowances: 4400,
    salary: 11000,
  },
  {
    id: "roster-42",
    fullName: "John Carlo Oconer",
    firstName: "John",
    lastName: "Oconer",
    nationality: "Filipino",
    dateOfBirth: "1983-06-26",
    joiningDate: "2025-11-17",
    position: "Sushi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 5400,
    allowances: 3600,
    salary: 9000,
  },
  {
    id: "roster-43",
    fullName: "Mark Joseph Acosta",
    firstName: "Mark",
    lastName: "Acosta",
    nationality: "Filipino",
    dateOfBirth: "1997-05-09",
    joiningDate: "2025-11-01",
    position: "Sushi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 5400,
    allowances: 3600,
    salary: 9000,
  },
  {
    id: "roster-44",
    fullName: "Mahendraraj Dilbahadur Rana",
    firstName: "Mahendraraj",
    lastName: "Rana",
    nationality: "Indian",
    dateOfBirth: "1991-12-25",
    joiningDate: "2025-11-01",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 3900,
    allowances: 2600,
    salary: 6500,
  },
  {
    id: "roster-45",
    fullName: "Rovin Singh",
    firstName: "Rovin",
    lastName: "Singh",
    nationality: "Indian",
    dateOfBirth: "1996-05-02",
    joiningDate: "2026-01-03",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-46",
    fullName: "Srikanth Nidamanuri",
    firstName: "Srikanth",
    lastName: "Nidamanuri",
    nationality: "N/A",
    dateOfBirth: "2026-07-06",
    joiningDate: "2025-11-01",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-47",
    fullName: "Suresh Lo Tamang",
    firstName: "Suresh",
    lastName: "Tamang",
    nationality: "Nepalese",
    dateOfBirth: "1989-01-15",
    joiningDate: "2025-11-01",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-48",
    fullName: "Yusarah Christiana",
    firstName: "Yusarah",
    lastName: "Christiana",
    nationality: "Indonesian",
    dateOfBirth: "1994-06-07",
    joiningDate: "2025-11-01",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 4800,
    allowances: 3200,
    salary: 8000,
  },
  {
    id: "roster-49",
    fullName: "Bikram Rana Magar",
    firstName: "Bikram",
    lastName: "Magar",
    nationality: "Nepalese",
    dateOfBirth: "2026-07-08",
    joiningDate: "2026-01-26",
    position: "Chef de Partie",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 4020,
    allowances: 2680,
    salary: 6700,
  },
  {
    id: "roster-50",
    fullName: "Nima Lama",
    firstName: "Nima",
    lastName: "Lama",
    nationality: "Nepalese",
    dateOfBirth: "",
    joiningDate: "2026-01-15",
    position: "Demi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-51",
    fullName: "Rachana Rai",
    firstName: "Rachana",
    lastName: "Rai",
    nationality: "Nepalese",
    dateOfBirth: "",
    joiningDate: "2023-06-12",
    position: "Demi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-52",
    fullName: "Sachin Singh Bisht",
    firstName: "Sachin",
    lastName: "Bisht",
    nationality: "Indian",
    dateOfBirth: "1991-10-10",
    joiningDate: "2025-11-01",
    position: "Demi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-53",
    fullName: "Sunil Rai",
    firstName: "Sunil",
    lastName: "Rai",
    nationality: "Nepalese",
    dateOfBirth: "1999-10-22",
    joiningDate: "2025-12-15",
    position: "Demi Chef",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 3000,
    allowances: 2000,
    salary: 5000,
  },
  {
    id: "roster-54",
    fullName: "Khagen Chapagain",
    firstName: "Khagen",
    lastName: "Chapagain",
    nationality: "Indian",
    dateOfBirth: "1987-03-21",
    joiningDate: "2026-02-23",
    position: "Goods-In",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2400,
    allowances: 1600,
    salary: 4000,
  },
  {
    id: "roster-55",
    fullName: "Akash Singh Kaintura",
    firstName: "Akash",
    lastName: "Kaintura",
    nationality: "N/A",
    dateOfBirth: "2000-07-20",
    joiningDate: "2026-02-05",
    position: "Commis 1",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-56",
    fullName: "Ankush Rawat",
    firstName: "Ankush",
    lastName: "Rawat",
    nationality: "Indian",
    dateOfBirth: "",
    joiningDate: "2025-11-03",
    position: "Commis 1",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2460,
    allowances: 1640,
    salary: 4100,
  },
  {
    id: "roster-57",
    fullName: "Deb Bahadur Paudel",
    firstName: "Deb",
    lastName: "Paudel",
    nationality: "Nepalese",
    dateOfBirth: "",
    joiningDate: "2023-06-15",
    position: "Commis 2",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-58",
    fullName: "Shashanika Gedara",
    firstName: "Shashanika",
    lastName: "Gedara",
    nationality: "Sri Lankan",
    dateOfBirth: "",
    joiningDate: "2026-01-05",
    position: "Commis 2",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2280,
    allowances: 1520,
    salary: 3800,
  },
  {
    id: "roster-59",
    fullName: "Anil Dahal",
    firstName: "Anil",
    lastName: "Dahal",
    nationality: "Nepalese",
    dateOfBirth: "1991-09-13",
    joiningDate: "2025-11-01",
    position: "Steward",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-60",
    fullName: "Bimal Singh Negi",
    firstName: "Bimal",
    lastName: "Negi",
    nationality: "Indian",
    dateOfBirth: "1994-05-18",
    joiningDate: "2025-10-20",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-61",
    fullName: "Harish Rawat",
    firstName: "Harish",
    lastName: "Rawat",
    nationality: "Indian",
    dateOfBirth: "2002-05-13",
    joiningDate: "2025-12-19",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-62",
    fullName: "Kolitha Hiran Gallage",
    firstName: "Kolitha",
    lastName: "Gallage",
    nationality: "Sri Lankan",
    dateOfBirth: "2026-05-14",
    joiningDate: "2025-11-25",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-63",
    fullName: "Sonam Gurung",
    firstName: "Sonam",
    lastName: "Gurung",
    nationality: "Nepalese",
    dateOfBirth: "",
    joiningDate: "2026-01-26",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-64",
    fullName: "Suraj Singh",
    firstName: "Suraj",
    lastName: "Singh",
    nationality: "Indian",
    dateOfBirth: "2006-01-02",
    joiningDate: "2026-02-21",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 2100,
    allowances: 1400,
    salary: 3500,
  },
  {
    id: "roster-65",
    fullName: "Lal Bahadur Tamang",
    firstName: "Lal",
    lastName: "Tamang",
    nationality: "Nepalese",
    dateOfBirth: "",
    joiningDate: "2025-11-01",
    position: "Commis 3",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 1980,
    allowances: 1320,
    salary: 3300,
  },
  {
    id: "roster-66",
    fullName: "Francis Muhumuza",
    firstName: "Francis",
    lastName: "Muhumuza",
    nationality: "Ugandan",
    dateOfBirth: "2026-07-02",
    joiningDate: "2026-02-16",
    position: "Steward",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 1680,
    allowances: 1120,
    salary: 2800,
  },
  {
    id: "roster-67",
    fullName: "Md Rois",
    firstName: "Md",
    lastName: "Rois",
    nationality: "N/A",
    dateOfBirth: "1983-01-07",
    joiningDate: "2025-11-01",
    position: "Steward",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 1680,
    allowances: 1120,
    salary: 2800,
  },
  {
    id: "roster-68",
    fullName: "Om Bhattrai",
    firstName: "Om",
    lastName: "Bhattrai",
    nationality: "Indian",
    dateOfBirth: "1997-07-29",
    joiningDate: "2025-12-24",
    position: "Steward",
    venue: "The MAINE Beach House",
    photo: null,
    basicSalary: 1680,
    allowances: 1120,
    salary: 2800,
  },
];
